---
apiVersion: v1
kind: Template
metadata:
  name: unleash
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: unleash
    name: unleash
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: unleash
    template:
      metadata:
        labels:
          app: unleash
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: unleash
          env:
            - name: ORG
              value: {{ org }}
            - name: TEAM
              value: {{ team }}
            - name: DATABASE_NAME
              value: {{ identifier }}
            - name: DATABASE_HOST
              valueFrom:
                 secretKeyRef:
                   name: unleash-rds
                   key: db.host
            - name: DATABASE_PORT
              valueFrom:
                 secretKeyRef:
                   name: unleash-rds
                   key: db.port
            - name: DATABASE_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: unleash-rds
                   key: db.user
            - name: DATABASE_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: unleash-rds
                   key: db.password
            - name: DEFAULT_DB
              valueFrom:
                secretKeyRef:
                  name: unleash-rds
                  key: db.name
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/oauth2
                  key: GH_CLIENT_ID
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/oauth2
                  key: GH_CLIENT_SECRET
            - name: GH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/oauth2
                  key: GH_CALLBACK_URL
            - name: ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/tokens
                  key: ADMIN_ACCESS_TOKEN
            - name: CLIENT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/tokens
                  key: CLIENT_ACCESS_TOKEN
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ identifier }}/tokens
                  key: SESSION_SECRET
          ports:
          - name: unleash
            containerPort: 4242
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
- apiVersion: v1
  kind: Service
  metadata:
    name: unleash
    labels:
      app: unleash
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 4242
        name: unleash
    selector:
      app: unleash

parameters:
- name: IMAGE
  value: quay.io/app-sre/unleash
  displayName: unleash image
  description: unleash docker image. Defaults to quay.io/app-sre/unleash
- name: IMAGE_TAG
  value: latest
  displayName: unleash version
  description: unleash version which defaults to latest
- name: MEMORY_REQUESTS
  value: 100Mi
- name: MEMORY_LIMIT
  value: 200Mi
- name: CPU_REQUESTS
  value: 50m
- name: CPU_LIMIT
  value: 100m
